[grid]
domain = [[0.0, 6.283185307179586]]  # 0 to 2Ï€
shape = [128]
periodic = [true]

[discretisation]
scheme = "spectral"
backend = "jax"

[model]
type = "advection"
velocity = [1.0]

[solver]
t0 = 0.0
t1 = 2.0  # one period of domain
dt0 = 0.05
solver = "Dopri5"
save_every = 10