[grid]
domain = [[0.0, 6.283185307179586]]
shape = [128]
periodic = [true]

[discretisation]
type = "spectral"
backend = "numpy"

[model]
type = "ideal_alfven"
[model.parameters]
B0 = 1.0

[simulation]
t0 = 0.0
t1 = 2.0
dt0 = 0.01

[initial_conditions]
v = { type = "sinusoidal", amplitude = 1.0, wavevector = [1], phase = 0.0 }
B = { type = "sinusoidal", amplitude = -1.0, wavevector = [1], phase = 0.0 }