[grid]
# One‑dimensional periodic domain for the Alfvén wave
domain = [(0.0, 6.283185307179586)]
shape = [128]
periodic = [true]

[discretisation]
type = "spectral"
backend = "numpy"

[model]
type = "ideal_alfven"
B0 = 1.0

[initial_conditions]
# Transverse velocity and magnetic field perturbations
v = { type = "sinusoidal", amplitude = -1.0, wavevector = [1], phase = 0.0 }
B = { type = "sinusoidal", amplitude = 1.0, wavevector = [1], phase = 0.0 }