[grid]
dimensions = [[0.0, 1.0], [0.0, '2*pi']]
resolution = [64, 64]
periodic = [false, true]

[discretisation]
type = "finite_difference"

[model]
type = "diffusion"
[model.parameters]
diffusivity = 0.05

[simulation]
t0 = 0.0
t1 = 0.1
dt0 = 0.001

[initial_conditions]
u = { type = "gaussian", amplitude = 1.0, center = [0.5, 'pi'], width = [0.1, 0.3] }