[grid]
# Two‑dimensional square domain with Dirichlet boundaries
domain = [(0.0, 1.0), (0.0, 1.0)]
shape = [32, 32]
periodic = [false, false]

[discretisation]
type = "finite_difference"
backend = "numpy"

[model]
type = "diffusion"
diffusivity = 0.1

[initial_conditions]
u = { type = "constant", value = 1.0 }