[grid]
dimensions = [[0.0, 1.0], [0.0, 1.0], [0.0, 1.0]]
resolution = [32, 32, 32]
periodic = [false, false, false]

[discretisation]
type = "finite_difference"

[model]
type = "diffusion"
[model.parameters]
diffusivity = 0.1

[simulation]
t0 = 0.0
t1 = 0.05
dt0 = 0.001

[initial_conditions]
u = { type = "gaussian", amplitude = 1.0, center = [0.5, 0.5, 0.5], width = 0.1 }