[grid]
# One‑dimensional spatial domain for drift‑kinetic model
domain = [(0.0, 6.283185307179586)]
shape = [64]
periodic = [true]

[discretisation]
type = "spectral"
backend = "numpy"

[model]
type = "drift_kinetic"
nv = 32
v_min = -4.0
v_max = 4.0

[initial_conditions]
f = { amplitude = 0.1, drift_velocity = 1.0, thermal_velocity = 1.0, background_density = 1.0 }