[grid]
dimensions = [[0.0, 2*pi]]
resolution = [64]
periodic = [true]

[discretisation]
type = "spectral"
backend = "numpy"

[model]
type = "vlasov"
[model.parameters]
nv = 64
v_min = -5.0
v_max = 5.0

[simulation]
t0 = 0.0
t1 = 2.0
dt0 = 0.1

[initial_conditions]
amplitude = 0.05
thermal_velocity = 0.5
drift_velocity = 2.0
background_density = 0.5