name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies (editable)
        run: |
          python -m pip install --upgrade pip
          # editable install ensures tests exercise the working tree
          python -m pip install -e '.[testing]'
          # optional: JAX CPU wheels if your tests import jax
          python -m pip install jax==0.4.25 jaxlib==0.4.25

      - name: Sanity check version (from Git tag)
        run: |
          python - <<'PY'
          import flexipde, importlib.metadata as im
          print("flexipde.__version__:", getattr(flexipde, "__version__", "MISSING"))
          print("pkg version:", im.version("flexipde"))
          PY

      - name: Run tests with coverage
        run: |
          python -m pytest --cov-branch --cov-report=xml --cov=flexipde

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: uwplasma/flexipde
          files: coverage.xml
